name: noting
description: Simple note app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  painter: ^0.4.0
  linked_scroll_controller: ^0.1.2
  keyboard_avoider: ^0.1.2
  floating_action_bubble: ^1.1.2
  hawk_fab_menu: ^0.3.2
  zefyr: ^0.12.0
  smoothie: ^0.2.0+1
  provider: ^4.3.2+3
  flutter_colorpicker: ^0.3.4
  simple_color_picker: ^1.0.0
  flutter_circle_color_picker: ^0.2.0
  image_picker: ^0.6.7+17
  flutter_fgbg: ^0.0.1
  intl: ^0.16.1
  screenshot: ^0.2.0
  image_gallery_saver: ^1.6.7
  admob_flutter: ^1.0.1
  sqflite: ^1.3.0
  path: ^1.7.0
  path_provider: ^1.6.24
  sembast: ^2.4.8+1
  get_it: ^4.0.2
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Naver
      fonts:
        - asset: assets/font/NanumSquareLight.ttf
          weight: 300
        - asset: assets/font/NanumSquareRegular.ttf
          weight: 500
        - asset: assets/font/NanumSquareBold.ttf
          weight: 700
        - asset: assets/font/NanumSquareExtraBold.ttf
          weight: 900

